name = "Anomaly"
uuid = "a40cd781-f393-47f2-8775-4fd2cd5a603c"
authors = ["Marcin Koculak <koculak.marcin@gmail.com>"]
version = "0.1.0-DEV"

[deps]
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
